// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EntittFramework_Project.Models;

#nullable disable

namespace EntittFramework_Project.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntittFramework_Project.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool?>("OnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            OnSale = true,
                            Picture = "1.jpg",
                            Price = 1030.00m,
                            ProductName = "Product 1",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 2,
                            OnSale = true,
                            Picture = "2.jpg",
                            Price = 1462.00m,
                            ProductName = "Product 2",
                            Size = 4
                        },
                        new
                        {
                            ProductId = 3,
                            OnSale = true,
                            Picture = "3.jpg",
                            Price = 1718.00m,
                            ProductName = "Product 3",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 4,
                            OnSale = true,
                            Picture = "4.jpg",
                            Price = 1289.00m,
                            ProductName = "Product 4",
                            Size = 1
                        },
                        new
                        {
                            ProductId = 5,
                            OnSale = true,
                            Picture = "5.jpg",
                            Price = 1288.00m,
                            ProductName = "Product 5",
                            Size = 4
                        });
                });

            modelBuilder.Entity("EntittFramework_Project.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            Date = new DateTime(2022, 5, 25, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4915),
                            ProductId = 1,
                            Quantity = 110
                        },
                        new
                        {
                            SaleId = 2,
                            Date = new DateTime(2023, 2, 8, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4948),
                            ProductId = 2,
                            Quantity = 152
                        },
                        new
                        {
                            SaleId = 3,
                            Date = new DateTime(2022, 9, 6, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4956),
                            ProductId = 3,
                            Quantity = 128
                        },
                        new
                        {
                            SaleId = 4,
                            Date = new DateTime(2023, 1, 9, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4964),
                            ProductId = 4,
                            Quantity = 250
                        },
                        new
                        {
                            SaleId = 5,
                            Date = new DateTime(2022, 11, 18, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4971),
                            ProductId = 5,
                            Quantity = 248
                        },
                        new
                        {
                            SaleId = 6,
                            Date = new DateTime(2022, 9, 14, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4979),
                            ProductId = 1,
                            Quantity = 232
                        },
                        new
                        {
                            SaleId = 7,
                            Date = new DateTime(2022, 7, 18, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4986),
                            ProductId = 2,
                            Quantity = 231
                        },
                        new
                        {
                            SaleId = 8,
                            Date = new DateTime(2022, 6, 30, 15, 27, 12, 899, DateTimeKind.Local).AddTicks(4993),
                            ProductId = 3,
                            Quantity = 210
                        });
                });

            modelBuilder.Entity("EntittFramework_Project.Models.Sale", b =>
                {
                    b.HasOne("EntittFramework_Project.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntittFramework_Project.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
